# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: SB_tutorial
# label used for menu selection
label: EDL Tag policy
description: using for a tutorial to show how to build skillets

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Tutorial

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: tag_name
    description: tag name
    default: mytag
    type_hint: text
  - name: tag_description
    description: tag description
    default: mytag description
    type_hint: text
  - name: tag_color
    description: tag color
    default: red
    type_hint: dropdown
    dd_list:
      - key: red
        value: color1
      - key: orange
        value: color6
  - name: edl_name
    description: EDL name
    default: myedl
    type_hint: text
  - name: edl_desc
    description: EDL description
    default: myedl description
    type_hint: test
  - name: edl_url
    description: EDL URL
    default: http://someurl.com
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: object_tag
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag
    element: |-
        <entry name="{{ tag_name }}">
                      <color>{{ tag_color }}</color>
                      <comments>{{ tag_description }}</comments>
                    </entry>

  - name: object_edl
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
        <external-list>
                    <entry name="{{ edl_name }}">
                      <type>
                        <ip>
                          <recurring>
                            <five-minute/>
                          </recurring>
                          <description>{{ edl_desc }}</description>
                          <url>{{ edl_url }}</url>
                        </ip>
                      </type>
                    </entry>
                  </external-list>

  - name: policy_security_outbound
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="{{ edl_name }}-out">
                          <to>
                            <member>any</member>
                          </to>
                          <from>
                            <member>any</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>{{ edl_name }}</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>any</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <tag>
                            <member>{{ tag_name }}</member>
                          </tag>
                          <action>deny</action>
                          <description> outbound EDL IP bock rule. EDL info: {{ edl_desc }}</description>
                          <log-setting>Log_Forwarding_to_Splunk_Algosec_Qradar</log-setting>
                        </entry>

  - name: security_policy_inbound
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="{{ edl_name }}-in">
                          <to>
                            <member>any</member>
                          </to>
                          <from>
                            <member>any</member>
                          </from>
                          <source>
                            <member>{{ edl_name }}</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>any</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <tag>
                            <member>{{ tag_name }}</member>
                          </tag>
                          <action>deny</action>
                          <description>{{ edl_desc }}</description>
                          <log-setting>Log_Forwarding_to_Splunk_Algosec_Qradar</log-setting>
                        </entry>


# ---------------------------------------------------------------------
# end of snippets section