name: sample_validation_skilletbuilder1
label: Sample Validation Skillet

description: |
  Short set of validations for skilletBuilder training tutorial with ntp check, password complexity,
  URL filtering for malware, and security allow rules with profiles or groups

type: pan_validation
labels:
  collection:
    - Skillet Builder
    - Validation

variables:

  - name: placeholder
    description: Some Parameter
    default: yes
    type_hint: hidden

snippets:

# get ntp server and password complexity objects
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: ntp_servers
        capture_object: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/ntp-servers
      - name: password_complexity
        capture_object: /config/mgt-config/password-complexity

# check that ntp servers are configured
  - name: ntp_servers_test
    label: configure primary and secondary ntp servers
    test: |
      (
      ntp_servers | tag_present('primary-ntp-server.ntp-server-address')
      and ntp_servers | tag_present('secondary-ntp-server.ntp-server-address')
      )
    fail_message: |
      time server configuration is reccommended to ensure the firewall clock is in sync with external service and logging
      platforms.
    pass_message: recommended primary and secondary ntp servers are configured
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#device-setup-services-services

 # check for password complexity minimum password length
  - name: password_complexity_test
    label: configure strong password complexity ( >= 12 chars)
    test: |
      (
      password_complexity | element_value('enabled') == 'yes'
      and password_complexity | element_value('minimum-length') >= '12'
      )
    fail_message: |
      check that password complexity is enabled with a minimum password length of 12 characters {{ password_complexity }}
    pass_message: |
      password complexity is enabled with a minimum password length of 12 characters
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html#device-setup-management-minimum-password-complexity

 # test that all url-filtering profiles block the category malware
  - name: url_profile_test
    cmd: parse
    variable: config
    outputs:
      # get list of all url profiles for debug example
      - name: url_filtering_profiles
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry/@name

      # get list of url profiles with malware explicitly set to block
      # using this model instead of checking for alert, allow, continue - especially with allow not showing in the config
      - name: url_profiles_block_malware
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry
          /block/member[text()='malware']/../../@name

      # get list of all url profiles then filter to profiles not in url_profiles_block_malware
      - name: url_profiles_not_blocking_malware
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry/@name
        filter_items: item not in url_profiles_block_malware

  # check that all url profiles are blocking malware
  - name: check_all_url_profiles_block_malware
    label: check that all url profiles block category malware
    test: url_profiles_not_blocking_malware | length == 0
    severity: high
    fail_message: |
      url profiles not blocking malware: {{ url_profiles_not_blocking_malware }}
    pass_message: |
      all url profiles are currently blocking the category malware
    documentation_link: https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/url-filtering/configure-url-filtering.html#

  # test that all allow security policies have a profile or profile-group configured
  - name: security_policy_test
    cmd: parse
    variable: config
    outputs:
      # get a list of security policies with a profile or group configured
      - name: security_policies_with_profile_or_group
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
          /rulebase/security/rules/entry/profile-setting/../@name

      # get a list of security policies with action allow
      - name: allow_security_policies_without_profile
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
          /rulebase/security/rules/entry/action[text()='allow']/../@name
        filter_items: item not in security_policies_with_profile_or_group

  # check that all allow security policies have a profile or group
  - name: check_allow_security_policies_have_profile
    label: check that all allow security policies have a profile or group
    test: allow_security_policies_without_profile | length == 0
    severity: medium
    fail_message: |
      allow security policies without a profile or group: {{ allow_security_policies_without_profile }}
    pass_message: |
      all allow security policies have a profile or group configured
    documentation_link: https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/policy/security-profiles/create-a-security-profile-group.html